// flow-typed signature: fc1e1a71f13a0f36fbc2ab2dd47a3457
// flow-typed version: <<STUB>>/aws-cognito-promises_v^1.0.4/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'aws-cognito-promises'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'aws-cognito-promises' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'aws-cognito-promises/dist/index' {
  declare module.exports: any;
}

declare module 'aws-cognito-promises/src/authenticate' {
  declare module.exports: any;
}

declare module 'aws-cognito-promises/src/config' {
  declare module.exports: any;
}

declare module 'aws-cognito-promises/src/confirmation' {
  declare module.exports: any;
}

declare module 'aws-cognito-promises/src/getAttributes' {
  declare module.exports: any;
}

declare module 'aws-cognito-promises/src/getDevice' {
  declare module.exports: any;
}

declare module 'aws-cognito-promises/src/getLocalUser' {
  declare module.exports: any;
}

declare module 'aws-cognito-promises/src/getSession' {
  declare module.exports: any;
}

declare module 'aws-cognito-promises/src/index' {
  declare module.exports: any;
}

declare module 'aws-cognito-promises/src/refreshCredentials' {
  declare module.exports: any;
}

declare module 'aws-cognito-promises/src/register' {
  declare module.exports: any;
}

declare module 'aws-cognito-promises/src/signOut' {
  declare module.exports: any;
}

declare module 'aws-cognito-promises/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'aws-cognito-promises/dist/index.js' {
  declare module.exports: $Exports<'aws-cognito-promises/dist/index'>;
}
declare module 'aws-cognito-promises/src/authenticate.js' {
  declare module.exports: $Exports<'aws-cognito-promises/src/authenticate'>;
}
declare module 'aws-cognito-promises/src/config.js' {
  declare module.exports: $Exports<'aws-cognito-promises/src/config'>;
}
declare module 'aws-cognito-promises/src/confirmation.js' {
  declare module.exports: $Exports<'aws-cognito-promises/src/confirmation'>;
}
declare module 'aws-cognito-promises/src/getAttributes.js' {
  declare module.exports: $Exports<'aws-cognito-promises/src/getAttributes'>;
}
declare module 'aws-cognito-promises/src/getDevice.js' {
  declare module.exports: $Exports<'aws-cognito-promises/src/getDevice'>;
}
declare module 'aws-cognito-promises/src/getLocalUser.js' {
  declare module.exports: $Exports<'aws-cognito-promises/src/getLocalUser'>;
}
declare module 'aws-cognito-promises/src/getSession.js' {
  declare module.exports: $Exports<'aws-cognito-promises/src/getSession'>;
}
declare module 'aws-cognito-promises/src/index.js' {
  declare module.exports: $Exports<'aws-cognito-promises/src/index'>;
}
declare module 'aws-cognito-promises/src/refreshCredentials.js' {
  declare module.exports: $Exports<'aws-cognito-promises/src/refreshCredentials'>;
}
declare module 'aws-cognito-promises/src/register.js' {
  declare module.exports: $Exports<'aws-cognito-promises/src/register'>;
}
declare module 'aws-cognito-promises/src/signOut.js' {
  declare module.exports: $Exports<'aws-cognito-promises/src/signOut'>;
}
declare module 'aws-cognito-promises/webpack.config.js' {
  declare module.exports: $Exports<'aws-cognito-promises/webpack.config'>;
}
